name: 'Avant Barber - Local'
values:
  - key: baseUrl
    value: 'http://localhost:8080'
    enabled: true
    type: default
  - key: barbeiroId
    value: '1'
    enabled: true
    type: default
  - key: clienteId
    value: '1'
    enabled: true
    type: default
  - key: servicoId
    value: '1'
    enabled: true
    type: default
