spring:
  application:
    name: avant

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/avant_barbearia}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root} # Se houver uma variável DB_PASSWORD, ela será usada. Senão, usa 'root'.

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 643979081631-ehumuvopjjnp7fvpre49dugnlum1dnl0.apps.googleusercontent.com

  spring:
    security:
      oauth2:
        client:
          registration:
            google:
              client-secret: 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