spring:
  application:
    name: avant

  datasource:
    url: jdbc:postgresql://localhost:5432/avant_barbearia
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 643979081631-ehumuvopjjnp7fvpre49dugnlum1dnl0.apps.googleusercontent.com

  spring:
    security:
      oauth2:
        client:
          registration:
            google:
              client-secret: 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