spring:
  application:
    name: avant

  datasource:
    url: jdbc:postgresql://localhost:5432/avant_barbearia
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ***REMOVIDO***

  spring:
    security:
      oauth2:
        client:
          registration:
            google:
              client-secret: ***REMOVED***